version: "3"
services:
  bot:
    container_name: bot
    image: ${IMAGE}
    expose:
      - "${SERVICE_PORT}"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
